web:
  image: node:latest
  volumes:
   - .:/usr/src/app
  links:
   - neo4j
  ports:
   - "3000:3000"
  command: sh -c 'npm install; npm install -g nodemon ; nodemon --watch routes --watch bin --watch views --watch app.js --watch bin/www -e js,jade bin/www'
  working_dir: /usr/src/app
  environment:
    - NODE_ENV=development
neo4j:
  image: neo4j:latest
  ports:
   - "7473:7473"
   - "7474:7474"
   - "7687:7687"
  volumes:
   - ./db:/data
