web:
  image: node:latest
  volumes:
   - .:/usr/src/app
  links:
   - neo4j
  ports:
   - "3000:3000"
  working_dir: /usr/src/app
  entrypoint: npm start
neo4j:
  image: neo4j:latest
  ports:
   - "7473:7473"
   - "7474:7474"
   - "7687:7687"
  volumes:
   - ./db:/data
